let SERVER_URL = 'http://localhost:4242';
try {
	// env.js is generated by running `node scripts/load-env.js`
	// It's excluded from git to avoid committing secrets.
	// If not present, we fall back to localhost.
	// eslint-disable-next-line global-require
	const env = require('./env');
	if (env && env.SERVER_URL) SERVER_URL = env.SERVER_URL;
} catch (err) {
	// ignore
}

export { SERVER_URL };
export default { SERVER_URL };